### ISSUE TITLE
Copyrighted files

### ISSUE THREAD

**Issue by TheHamkerCat** [szsupunma/sz-rosebot#3]
Why are you copy pasting the code of the developers and adding your copyright on it?

https://github.com/szsupunma/sz-rosebot/blob/9750d69e3238f68a5253ef90ff5d7ddb86d4695d/Rose/core/keyboard.py#L1-L4

Many modules of your bot is taken from [WilliamButcherBot](https://github.com/TheHamkerCat/WilliamButcherBot) which is written by me, and you're adding your own copyright on it.

**Comment by szsupunma** [comment]
No vro i will update this soon with multi  lang
Sorry for this mistake but i was give all credits in docs
